const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.bound,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Behaviors.Bullet,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.ScriptsInEvents.Sistemajogo_Event2_Act4,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{fundo: 0},
	{Sólido: 0},
	{chão: 0},
	{proximaFase: 0},
	{espinho: 0},
	{RestritoAoLayout: 0},
	{Plataforma: 0},
	{léo: 0},
	{bolaDeLã: 0},
	{Teclado: 0},
	{pistasDoGato: 0},
	{textCoracoes: 0},
	{vida: 0},
	{Áudio: 0},
	{fundo2: 0},
	{rocha: 0},
	{chãoInvisivl: 0},
	{aliadoDoRuffus: 0},
	{Projétil: 0},
	{poder: 0},
	{portal: 0},
	{fundo3: 0},
	{chão2: 0},
	{chão3: 0},
	{ruffus: 0},
	{mingau: 0},
	{BECKGROUND: 0},
	{START: 0},
	{MINGAUCADEVOCE: 0},
	{CRIADOPORCAUA: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{gameOver: 0},
	{TENTANOVAMENTE: 0},
	{DEVOLTAAOMENU: 0},
	{TELADOVENCEDOR: 0},
	{Sprite5: 0},
	{voltarAoMenu: 0},
	{dundovencedor: 0},
	{vocêVeceu: 0},
	{vidas: 0}
];

self.InstanceType = {
	fundo: class extends self.ISpriteInstance {},
	chão: class extends self.ISpriteInstance {},
	proximaFase: class extends self.ISpriteInstance {},
	espinho: class extends self.ISpriteInstance {},
	léo: class extends self.ISpriteInstance {},
	bolaDeLã: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	pistasDoGato: class extends self.ISpriteFontInstance {},
	textCoracoes: class extends self.ISpriteFontInstance {},
	vida: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	fundo2: class extends self.ISpriteInstance {},
	rocha: class extends self.ISpriteInstance {},
	chãoInvisivl: class extends self.ISpriteInstance {},
	aliadoDoRuffus: class extends self.ISpriteInstance {},
	poder: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	fundo3: class extends self.ISpriteInstance {},
	chão2: class extends self.ISpriteInstance {},
	chão3: class extends self.ISpriteInstance {},
	ruffus: class extends self.ISpriteInstance {},
	mingau: class extends self.ISpriteInstance {},
	BECKGROUND: class extends self.ISpriteInstance {},
	START: class extends self.IButtonInstance {},
	MINGAUCADEVOCE: class extends self.ITextInstance {},
	CRIADOPORCAUA: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	gameOver: class extends self.ITextInstance {},
	TENTANOVAMENTE: class extends self.IButtonInstance {},
	DEVOLTAAOMENU: class extends self.IButtonInstance {},
	TELADOVENCEDOR: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	voltarAoMenu: class extends self.IButtonInstance {},
	dundovencedor: class extends self.ISpriteInstance {},
	vocêVeceu: class extends self.ITextInstance {}
}